---
title: "Rough draft blog"
author: "Allie Cole"
date: "11/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#getting libraries using librian 

if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}
librarian::shelf(
  clockify, dplyr, lubridate, metajam, here, tidyverse, Hmisc, kableExtra, xtable, readr)
```

```{r}
#Uganda Beauro of Stats 
ug_secondaryGER <-read_csv(here("data", "GER_Secondary_Enrollment_Rates_By_District.csv"), 
                           na.omit("region"),
                           na = "-", 
                           col_types = cols(`2012` = col_number(), 
                                            `2013` = col_number(), 
                                            `2014` = col_number(), 
                                            `2015` = col_number(), 
                                            `2016` = col_number(),
                                            `2017` = col_number())) %>% 
  pivot_longer(!District, names_to = "Years", values_to = "GER") %>% 
  mutate(
    region = case_when(
      District %in% c("Abim","Adjumani", "Agago", "Alebtong", "Amolatar", "Amudat", "Amuru", "Apac", "Arua", "Dokolo", "Gulu", "Kaabong", "Kitgum", "Koboko"  , "Kole", 	"Kotido", "Lamwo",	"Lira", "Maracha",	"Moroto", "Moyo",	"Nakapiripirit", "Napak",	"Nebbi", "Nwoya",	"Otuke", "Oyam",	"Pader",	"Yumbe",	"Zombo")  ~ "Northern", 
      
      District %in% c("Buikwe", "Bukomansimbi", "Butambala", "Buvuma", "Gomba", "Kalangala", "Kalungu", "Kampala", "Kasanda", "Kayunga", "Kiboga", "Kyankwanzi", "Kyotera", "Luweero", "Lwengo", "Lyantonde", "Masaka", "Mityana", "Mpigi", "Mubende", "Mukono", "Nakaseke", "Nakasongola", "Rakai", "Sembabule", "Wakiso") ~ "Central",
      District %in% c("Amuria", "Budaka", "Bududa", "Bugiri", "Bugweri", "Bukedea", "Bukwo", "Bulambuli",   "Busia",       "Butaleja",    "Butebo" ,    "Buyende"  ,   "Iganga"  ,    "Jinja"  ,"Kaberamaido", "Kaliro"  ,    "Kamuli" ,     "Kapchorwa"  , "Kapelebyong" ,"Katakwi"  ,   "Kibuku", "Kumim",       "Kween" ,      "Luuka",       "Manafwa" ,    "Mayuge",      "Mbale",       "Namayingo", "Namisindwa",  "Namutumba" ,  "Ngora" ,      "Pallisa" ,    "Serere" ,     "Sironko" ,    "Soroti" ,"Tororo" ) ~ "Eastern", 
      District %in% c("Buhweju", "Buliisa","Bundibugyo","Bunyangabu","Bushenyi","Hoima" ,"Ibanda",
                      "Isingiro" ,"Kabale" , "Kabarole" ,"Kagadi" ,"Kakumiro" ,"Kamwenge","Kanungu",
                      "Kasese" ,"Kazo", "Kibaale","Kikuube" ,"Kiruhura","Kiryandongo", "Kisoro", "Kitagwenda",  "Kyegegwa", "Kyenjojo", "Masindi" ,"Mbarara","Mitooma","Ntoroko" , "Ntungamo" ,   "Rubanda"  ,   "Rubirizi" ,   "Rukiga" ,     "Rukungiri" ,  "Rwampara" ,   "Sheema") ~ "Western"
    ))

ug_secondaryNER <-read_csv(here("data", "NER_Secondary_Enrollment_Rates_By_District.csv"), na = "-", 
                           col_types = cols(`2012` = col_number(), 
                                            `2013` = col_number(), 
                                            `2014` = col_number(), 
                                            `2015` = col_number(), 
                                            `2016` = col_number(),
                                            `2017` = col_number())) %>% 
  pivot_longer(!District, names_to = "Years", values_to = "NER") %>% 
   mutate(
    region = case_when(
      District %in% c("Abim","Adjumani", "Agago", "Alebtong", "Amolatar", "Amudat", "Amuru", "Apac", "Arua", "Dokolo", "Gulu", "Kaabong", "Kitgum", "Koboko"  , "Kole", 	"Kotido", "Lamwo",	"Lira", "Maracha",	"Moroto", "Moyo",	"Nakapiripirit", "Napak",	"Nebbi", "Nwoya",	"Otuke", "Oyam",	"Pader",	"Yumbe",	"Zombo")  ~ "Northern", 
      
      District %in% c("Buikwe", "Bukomansimbi", "Butambala", "Buvuma", "Gomba", "Kalangala", "Kalungu", "Kampala", "Kasanda", "Kayunga", "Kiboga", "Kyankwanzi", "Kyotera", "Luweero", "Lwengo", "Lyantonde", "Masaka", "Mityana", "Mpigi", "Mubende", "Mukono", "Nakaseke", "Nakasongola", "Rakai", "Sembabule", "Wakiso") ~ "Central",
      District %in% c("Amuria", "Budaka", "Bududa", "Bugiri", "Bugweri", "Bukedea", "Bukwo", "Bulambuli",   "Busia",       "Butaleja",    "Butebo" ,    "Buyende"  ,   "Iganga"  ,    "Jinja"  ,"Kaberamaido", "Kaliro"  ,    "Kamuli" ,     "Kapchorwa"  , "Kapelebyong" ,"Katakwi"  ,   "Kibuku", "Kumim",       "Kween" ,      "Luuka",       "Manafwa" ,    "Mayuge",      "Mbale",       "Namayingo", "Namisindwa",  "Namutumba" ,  "Ngora" ,      "Pallisa" ,    "Serere" ,     "Sironko" ,    "Soroti" ,"Tororo" ) ~ "Eastern", 
      District %in% c("Buhweju", "Buliisa","Bundibugyo","Bunyangabu","Bushenyi","Hoima" ,"Ibanda",
                      "Isingiro" ,"Kabale" , "Kabarole" ,"Kagadi" ,"Kakumiro" ,"Kamwenge","Kanungu",
                      "Kasese" ,"Kazo", "Kibaale","Kikuube" ,"Kiruhura","Kiryandongo", "Kisoro", "Kitagwenda",  "Kyegegwa", "Kyenjojo", "Masindi" ,"Mbarara","Mitooma","Ntoroko" , "Ntungamo" ,   "Rubanda"  ,   "Rubirizi" ,   "Rukiga" ,     "Rukungiri" ,  "Rwampara" ,   "Sheema") ~ "Western"
    ))
```


```{r}
### World food program Food prices 

wfp_food_prices_uga_raw <- read_csv("data/wfp_food_prices_uga.csv", 
    col_types = cols(admin2 = col_skip(), 
        latitude = col_skip(), longitude = col_skip(), 
        category = col_skip())) %>% 
  mutate(date = lubridate::ymd(date))

fp <- wfp_food_prices_uga_raw[-1,]

#%>% 
  filter(date >= as.Date("2012-01-01") & date <= as.Date(2017-12-31))
```

```{r}

primary <-read_csv(here("data", "Primary_13-16.csv"))
```


```{r}
ggplot(data = primary, aes(x = Year, y = Number, col = Schooling)) +
  geom_point() +
  theme_minimal() +
  scale_y_log10(
    "Total students enrolled",
    labels = scales::label_number_si()) +
   labs(x = "Year",
       y = "Total students enrolled",
       title = "Uganda Primary School Enrollment by Year")
```


```{r}
ggplot(data = ug_secondaryGER, aes(x = Years, y = GER, col = region)) +
  geom_point() +
  theme_minimal() +
   labs(x = "Year",
       y = "Gross Enrollment Rate",
       title = "Rate of Secondary School Enrollment by Region")
```

```{r}
#will disrtict hav ean affect on number of children who attend school?

 lm(GER ~ District, data = ug_secondaryGER)  %>%
  summary() %>% 
  xtable() %>% 
  kable(caption = "Think Of a Captaion", digits = 4)

```

```{r}
#Will the year have an effect on number of children who attend school?

lm(GER ~ Years, data = ug_secondaryGER) %>% 
  summary()
```



```{r}


 lm(Number ~ Sex + Schooling, data = primary)  %>% 
  summary()
  
  #%>%
  summary() %>% 
  xtable() %>% 
  kable(caption = "Think Of a Captaion", digits = 4)
```


